version: "3.4"
services:
  frontend:
    container_name: frontend
    image: node:lts
    working_dir: /var/www/html/app/frontend
    ports:
      - 8000:8000
    volumes:
      - ./app/:/var/www/html/app
    tty: true
    command:
      npm run dev